### PR TITLE
Provide variadic function call operator for val

### PR DESCRIPTION
**Pull request by rileylev**
The function call operator in val.hpp can be written to use variadic arguments. 
The implementation here uses fold expressions from C++17, but everything except the static assert conforms to C++14 I believe.

### CODE REVIEW

**Comment by arximboldi** [comment]
Hi @rilerez !

Thanks a lot for your valuable contribution!

My main concern is that you changed the style of the whole file, even changing the amount of spacing in the indetation. This is general advise when contributing to an OSS project: try to keep your contributions minimal and not make stylistic changes. Also, in the new code that you introduce, keep the style consistent with the other code you see around it.

Also, I see you added operators ==/!= for the value wrapper, was that needed for some reason?

Also: since val only contains an SCM inside, which is basically just a pointer, doing perfect forwarding just adds noise to the function. Please take by value instead of && and avoid std::forward().

Finally, I suspect that `scm_call_N` is slightly faster than the variadic `scm_call`. For that reason, I would suggest to keep the existing overloads, such that your method is used as a backup for the general case.

Once again, thanks a lot! If you make the changes above, I think I would be happy to merge it eventually.

**Comment by rileylev** [comment]
No problem! Sorry about the style changes, I just ran clang format over the whole file carelessly.  I think I committed the new operators by mistake. I think for the scm_call_n operators, it would be best to put them in an if constexpr so implicitly convertible arguments don't get grabbed by the general case.

Is it better to push this the correted version to dev than master?

**Comment by arximboldi** [comment]
Hi @rilerez, this is starting to look real good, almost ready to go! One last thing, I think you reverted by mistake an extra commit. Can you drop the commit `a2f3f98`? Thanks!

**Comment by rileylev** [comment]
Ok I think I got it now!

**Comment by arximboldi** [comment]
Thanks a lot for all the effort in cleaning up the PR.

There seems to be another issue... :scream: Travis checks are failing, since we were until now using C++14.

Since this project is relatively experimental, it would be possible to up the requirements to C++17. On the other hand, the change does not seem to fundamentally require C++17 (other than, a C++14 solution would obviously be more verbose). Would it be ok for you to rewrite the change to make it C++14 compatible?

**Comment by rileylev** [comment]
I think the template dispatching tricks needed to make this work in C++14 complicate the code a lot. I got it working, though. I just accidentally overwrote the file. I can redo it and push again.

**Comment by rileylev** [comment]
hmm these seem to only work on later versions of the compilers. I can define matching overloads for each arity from 0 to 9 to be compatible with the old compilers, but it will have tons of code duplication that way, so I'm inclined to avoid that.

**Comment by arximboldi** [comment]
Hi Rilerez! Thanks a lot for all the effort you are putting into this PR. Your solution is definitely very creative indeed! Sadly, the compiler is right in complaining about the mismatching return types---solving that requires `if constexpr` and C++17. I am inclined to believe that, although less elegant, using overloads is the most robust way of implementing this.

**Comment by rileylev** [comment]
Ok I'll give it a shot!

**Comment by arximboldi** [comment]
Nice! Seems to be working and Travis is happy about it. Time to merge! Thanks again for all the effort in getting this ready!

**Pull request merged**
